spring:
  profiles:
    active: usage_message
  rabbitmq:
    host: localhost
    port: 5673

logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000
    message: Headers Message
    temperature: hot
    color: white

